---
name: "Email"
guid: "cfa0f7f4-4155-4d71-849b-d6598dc4c5bb"
version: "7.0.0.0"
targetAbi: "10.6.0.0"
owner: "jellyfin"
overview: "Send SMTP email notifications"
description: "Send SMTP email notifications"
category: "Notifications"
artifacts:
- "MediaBrowser.Plugins.SmtpNotifications.dll"
changelog: >
  changelog
